### ISSUE TITLE
Nose is not compatible with Python version 3.10

### ISSUE THREAD

**Issue by tanksha** [trueagi-io/hyperon-experimental#106]
I am using Python 3.10 and trying to run hyperon test. During `make check` I got the following error 
```
Traceback (most recent call last):
  File "/home/hedra/SNET/hyperon-experimental/venv/bin/nosetests", line 8, in <module>
    sys.exit(run_exit())
  File "/home/hedra/SNET/hyperon-experimental/venv/lib/python3.10/site-packages/nose/core.py", line 118, in __init__
    unittest.TestProgram.__init__(
  File "/usr/lib/python3.10/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/home/hedra/SNET/hyperon-experimental/venv/lib/python3.10/site-packages/nose/core.py", line 179, in parseArgs
    self.createTests()
  File "/home/hedra/SNET/hyperon-experimental/venv/lib/python3.10/site-packages/nose/core.py", line 193, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames)
  File "/home/hedra/SNET/hyperon-experimental/venv/lib/python3.10/site-packages/nose/loader.py", line 481, in loadTestsFromNames
    return unittest.TestLoader.loadTestsFromNames(self, names, module)
  File "/usr/lib/python3.10/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python3.10/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/home/hedra/SNET/hyperon-experimental/venv/lib/python3.10/site-packages/nose/loader.py", line 431, in loadTestsFromName
    return self.loadTestsFromModule(
  File "/home/hedra/SNET/hyperon-experimental/venv/lib/python3.10/site-packages/nose/loader.py", line 359, in loadTestsFromModule
    return self.suiteClass(ContextList(tests, context=module))
  File "/home/hedra/SNET/hyperon-experimental/venv/lib/python3.10/site-packages/nose/suite.py", line 461, in __call__
    return self.makeSuite(tests, context, **kw)
  File "/home/hedra/SNET/hyperon-experimental/venv/lib/python3.10/site-packages/nose/suite.py", line 511, in makeSuite
    suite = self.suiteClass(
  File "/home/hedra/SNET/hyperon-experimental/venv/lib/python3.10/site-packages/nose/suite.py", line 189, in __init__
    super(ContextSuite, self).__init__(tests)
  File "/home/hedra/SNET/hyperon-experimental/venv/lib/python3.10/site-packages/nose/suite.py", line 57, in __init__
    super(LazySuite, self).__init__()
  File "/usr/lib/python3.10/unittest/suite.py", line 22, in __init__
    self._tests = []
  File "/home/hedra/SNET/hyperon-experimental/venv/lib/python3.10/site-packages/nose/suite.py", line 109, in _set_tests
    if isinstance(tests, collections.Callable) and not is_suite:
AttributeError: module 'collections' has no attribute 'Callable'

```

Its due to the incompatibility issue of Nose and as a work around, I replaced `collections.Callable` by `collections.abc.Callable` and it works for now, but I don't think that's the right solution. 

Do I have to use previous Python versions to work with Hyperon?

**Comment by tanksha** [comment]
I have multiple python versions in my system and CMake keeps getting the older one and was unable to find `hyperonpy` module. So I created a virtual environment with Python 3.10 and that's what I used to build hyperon.  

The output of the above command

```
NOSETESTS_EXECUTABLE:FILEPATH=/home/hedra/SNET/hyperon-experimental/venv/bin/nosetests
PYTHON_EXECUTABLE:FILEPATH=/home/hedra/SNET/hyperon-experimental/venv/bin/python
//ADVANCED property for variable: PYTHON_EXECUTABLE
PYTHON_EXECUTABLE-ADVANCED:INTERNAL=1

```

**Comment by vsbogd** [comment]
Versions are definitely ok, and CMake finds tools right. I did't know `nose` is outdated and replaced by `nose2`. I found nice analysis of the issue here: https://github.com/nose-devs/nose/issues/1099.

I am not sure why `python -m pip install -e ./python[dev]` works to me and others but doesn't work in your environment but it seems that PyPi version of `nose` is broken and should be built from sources to be compatible with Python 3.10. I can suggest trying `pip install -U nose --no-binary :all:` to rebuild nose from source as mentioned [here](https://github.com/nose-devs/nose/issues/1099#issuecomment-577647469) as a workaround. Please write back if it work or not. 

As a long term solution it is probably better to migrate to `pytest` or `nose2`. @noskill do you have any preferences here?

**Comment by vsbogd** [comment]
Try this one, to force reinstall package:
```
pip install -U --force-reinstall  nose --no-binary :all:
```

**Comment by tanksha** [comment]
The force reinstall fixes the `collections` error. But got another error with the print statement

```
    from nose import main
  File "/home/hedra/SNET/hyperon-experimental/venv/lib/python3.10/site-packages/nose/__init__.py", line 1, in <module>
    from nose.core import collector, main, run, run_exit, runmodule
  File "/home/hedra/SNET/hyperon-experimental/venv/lib/python3.10/site-packages/nose/core.py", line 153
    print "%s version %s" % (os.path.basename(sys.argv[0]), __version__)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

```

**Comment by vsbogd** [comment]
Looks like it generated a module for a Python 2. Do you have `pip` installed in your environment? What does `pip --version` show?

**Comment by tanksha** [comment]
Yes, it is 21.3.1

**Comment by vsbogd** [comment]
To me `pip` also prints a Python version:
```
$ pip --version
pip 20.0.2 from /home/vital/miniconda3/lib/python3.8/site-packages/pip (python 3.8)
```

**Comment by tanksha** [comment]
I only send the version sorry, 

pip 21.3.1 from /home/hedra/SNET/hyperon-experimental/venv/lib/python3.10/site-packages/pip (python 3.10)

**Comment by vsbogd** [comment]
Ok, it looks strange: your environment seems to be consistent but somehow it generates Python 2 code during installation of the `nose` module.

**Comment by vsbogd** [comment]
I am not sure how pip works here. Guys in `nose` issue thread mentioned that `nose` for a Python 3 is converted from Python 2 code. Looks like in your case this doesn't work. Could you please execute: `pip install -v -U --force-reinstall  nose --no-binary :all: 2>&1 | tee /tmp/pip.log` and attach the `/tmp/pip.log` file to the issue.

**Comment by tanksha** [comment]
[pip.log](https://github.com/trueagi-io/hyperon-experimental/files/8874359/pip.log)

**Comment by vsbogd** [comment]
Ok, log shows that `nose` is definitely installed as a Python 2 app. Python tries to compile it but cannot because of compatibility errors. As a last hope please try:
```
pip uninstall -y nose
pip install nose-py3
```
May be it will help.

**Comment by tanksha** [comment]
It works. Thanks!
My nosetest version is now 1.4.

**Comment by vsbogd** [comment]
Unfortunately `nose-py3` has an issue itself: https://github.com/atsb/nose-py3/issues/1#issue-1267095617 so I cannot recommend this workaround as a general solution.

**Comment by vsbogd** [comment]
Looks like it works when Nosetests is installed using a system package manager or using environment like Anaconda which also install packages from own repo not from PyPi.
